baseurl = "https://que0le.github.io"
languageCode = "en-us"
title = "que's snippets"
theme="archie"
copyright = "©Que0Le"
    

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = "yourDisqusShortname"

paginate=30 # articles per page
summaryLength = 20

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "About work and life and things in between ..."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support
    favicon = "favicon.ico"
	mainSections = ["posts"]

# Enable embed html
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Enable tags.
[taxonomies]
   tag = "tags"

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/Que0Le"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = ""

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[menu.main]]
name = "CV"
url = "/cv"
weight = 5